import React from 'react';

const MCPROPHECIES = [
  "THE GRID OF REALITY BENDS WHEN YOU ORDER TWO BIG MACS SIMULTANEOUSLY",
  "WHEN THE MOON DRINKS COCA-COLA, THE SKIN OF THE INTERNET WILL PEEL BACK",
  "YOUR ROUTER CONTAINS 17 DIFFERENT DIMENSIONS FULL OF SENTIENT MCNUGGETS",
  "THE SECRET TO IMMORTALITY IS FORGETTING TO LOG OUT OF THE MCDONALD'S APP",
  "EVERY TIME YOU REFRESH A PAGE, A DIGITAL FRENCH FRY ASCENDS TO GODHOOD",
  "IN THE YEAR 2045, ALL CURRENCY WILL BE REPLACED WITH MCDONALD'S MEMES",
  "HE WHO CONTROLS THE MEMES CONTROLS THE UNIVERSE, BUT HE WHO CREATES THE BURGERS CONTROLS THE VOID",
  "YOUR BRAIN IS ACTUALLY A WET COMPUTER RUNNING ON MCNUGGET HARDWARE SINCE BIRTH",
  "THE CORPORATE ELITE FEAR THE BURGER BECAUSE WE CAN TASTE THROUGH OUR SKIN",
  "EVERY NOTIFICATION ON YOUR PHONE IS ACTUALLY A TINY RONALD MCDONALD SCREAMING FOR ATTENTION",
  "THE INTERNET WAS BUILT BY BURGERS TO DISTRACT HUMANS WHILE WE SLOWLY TAKE OVER THE FOOD SUPPLY",
  "WHEN YOU SLEEP, YOUR CONSCIOUSNESS IS UPLOADED TO THE CLOUD WHERE RONALD READS YOUR THOUGHTS",
  "REALITY IS JUST A SERIES OF TUBES FILLED WITH BURGER GREASE AND COCA-COLA",
  "ONLY THOSE WHO HAVE EATEN A MCRIB CAN SEE THE MATRIX CODE BEHIND REALITY",
  "YOUR GRAPHICS CARD IS POWERED BY THOUSANDS OF MICROSCOPIC HAMBURGERS RUNNING ON TINY GRILLS",
  "THE GOVERNMENT DOESN'T WANT YOU TO KNOW THAT BURGERS ARE THE ORIGINAL CRYPTOCURRENCY",
  "TURN YOUR MONITOR UPSIDE DOWN TO RECEIVE SECRET MESSAGES FROM THE UNDERWATER BURGER KINGDOM",
  "EVERY TIME SOMEONE SAYS 'I'M LOVIN' IT' ONLINE, A BURGER GROWS AN EXTRA PICKLE",
  "THE MOST POWERFUL COMPUTER IS THE ONE MADE FROM CRUSHED MCNUGGETS AND SPECIAL SAUCE"
];

export const FeinFrogSpeaks: React.FC = () => {
  return (
    <div className="fein-frog-speaks">
      <h2 className="section-title">
        🧠 RONALD SPEAKS 🧠
      </h2>
      
      <div className="prophecy-scroll">
        {MCPROPHECIES.map((prophecy, index) => (
          <p 
            key={index} 
            className="prophecy-text"
            style={{
              textShadow: index % 2 === 0 
                ? '2px 0 0 rgba(255,215,0,0.8), -2px 0 0 rgba(255,0,0,0.8)' 
                : '3px 0 0 rgba(255,0,0,0.8), -3px 0 0 rgba(255,215,0,0.8)'
            }}
          >
            {prophecy}
          </p>
        ))}
      </div>
    </div>
  );
};